// <auto-generated />
using System;
using CoffeeShopManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShopManagement.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    partial class CoffeeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietCombo", b =>
                {
                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCombo", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietCombo", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCthd"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCthd")
                        .HasName("PK__ChiTietH__1E4FA7716BC7F702");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietHoaDonLuaChon", b =>
                {
                    b.Property<int>("MaCthd")
                        .HasColumnType("int")
                        .HasColumnName("MaCTHD");

                    b.Property<int>("MaLuaChon")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaThem")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaCthd", "MaLuaChon")
                        .HasName("PK__ChiTietH__87D4A8EE2901ACB1");

                    b.HasIndex("MaLuaChon");

                    b.ToTable("ChiTietHoaDon_LuaChon", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.Combo", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCombo"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaCombo");

                    b.ToTable("Combo");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHd")
                        .HasName("PK__HoaDon__2725A6E0D01897CE");

                    b.HasIndex("MaKh");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.IceLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__IceLevel__3214EC07B8328FFD");

                    b.ToTable("IceLevel", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E040423DE");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.KhachHangVoucher", b =>
                {
                    b.Property<int>("MaKhVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKHVoucher");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhVoucher"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<int>("MaVoucher")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("datetime");

                    b.HasKey("MaKhVoucher");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaVoucher");

                    b.ToTable("KhachHangVoucher", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSanP__730A57592E50CAAC");

                    b.ToTable("LoaiSanPham", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.LuaChonMon", b =>
                {
                    b.Property<int>("MaLuaChon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuaChon"));

                    b.Property<decimal>("GiaThem")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("MaTuyChon")
                        .HasColumnType("int");

                    b.Property<string>("TenLuaChon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaLuaChon")
                        .HasName("PK__LuaChonM__99B0F9F8B9DAF7FE");

                    b.HasIndex("MaTuyChon");

                    b.ToTable("LuaChonMon", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A71DD95D8");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ProductOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowIce")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSize")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSugar")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTopping")
                        .HasColumnType("bit");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.HasKey("Id")
                        .HasName("PK__ProductO__3214EC079A2771EA");

                    b.HasIndex("MaSp");

                    b.ToTable("ProductOption", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaThem")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__ProductS__3214EC0765051DA0");

                    b.HasIndex("MaSp");

                    b.ToTable("ProductSize", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ProductTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaThem")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ProductT__3214EC0794F0657D");

                    b.ToTable("ProductTopping", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<bool>("DangKhuyenMai")
                        .HasColumnType("bit");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C8E8DB98B");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.SugarLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SugarLev__3214EC074600FA23");

                    b.ToTable("SugarLevel", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ThanhVien", b =>
                {
                    b.Property<int>("MaTv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTv"));

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaThanhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTv");

                    b.HasIndex("MaKh");

                    b.ToTable("ThanhVien", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.TuyChonMon", b =>
                {
                    b.Property<int>("MaTuyChon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuyChon"));

                    b.Property<bool>("BatBuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ChonToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TenTuyChon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaTuyChon")
                        .HasName("PK__TuyChonM__32F262619597F393");

                    b.ToTable("TuyChonMon", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.Voucher", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVoucher"));

                    b.Property<decimal>("DonToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaVoucher");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("LoaiSanPhamTuyChonMon", b =>
                {
                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaTuyChon")
                        .HasColumnType("int");

                    b.HasKey("MaLoai", "MaTuyChon")
                        .HasName("PK__LoaiSanP__7025717FBDE273E6");

                    b.HasIndex("MaTuyChon");

                    b.ToTable("LoaiSanPham_TuyChonMon", (string)null);
                });

            modelBuilder.Entity("ProductProductTopping", b =>
                {
                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("ToppingId")
                        .HasColumnType("int");

                    b.HasKey("MaSp", "ToppingId")
                        .HasName("PK__ProductP__69C524D4DF9D211F");

                    b.HasIndex("ToppingId");

                    b.ToTable("ProductProductTopping", (string)null);
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietCombo", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.Combo", "Combo")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShopManagement.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_HoaDon");

                    b.HasOne("CoffeeShopManagement.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_CTHD_SanPham");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietHoaDonLuaChon", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.ChiTietHoaDon", "MaCthdNavigation")
                        .WithMany("ChiTietHoaDonLuaChons")
                        .HasForeignKey("MaCthd")
                        .IsRequired()
                        .HasConstraintName("FK_CTHDLC_CTHD");

                    b.HasOne("CoffeeShopManagement.Models.LuaChonMon", "MaLuaChonNavigation")
                        .WithMany("ChiTietHoaDonLuaChons")
                        .HasForeignKey("MaLuaChon")
                        .IsRequired()
                        .HasConstraintName("FK_CTHDLC_LCM");

                    b.Navigation("MaCthdNavigation");

                    b.Navigation("MaLuaChonNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.HoaDon", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.KhachHangVoucher", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.KhachHang", "MaKhNavigation")
                        .WithMany()
                        .HasForeignKey("MaKh")
                        .IsRequired();

                    b.HasOne("CoffeeShopManagement.Models.Voucher", "MaVoucherNavigation")
                        .WithMany("KhachHangVouchers")
                        .HasForeignKey("MaVoucher")
                        .IsRequired();

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaVoucherNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.LuaChonMon", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.TuyChonMon", "MaTuyChonNavigation")
                        .WithMany("LuaChonMons")
                        .HasForeignKey("MaTuyChon")
                        .IsRequired()
                        .HasConstraintName("FK_LuaChonMon_TuyChonMon");

                    b.Navigation("MaTuyChonNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ProductOption", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.SanPham", "MaSpNavigation")
                        .WithMany("ProductOptions")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_ProductOption_SanPham");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ProductSize", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.SanPham", "MaSpNavigation")
                        .WithMany("ProductSizes")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_ProductSize_SanPham");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.SanPham", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_LoaiSanPham");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ThanhVien", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.KhachHang", "MaKhNavigation")
                        .WithMany()
                        .HasForeignKey("MaKh")
                        .IsRequired();

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("LoaiSanPhamTuyChonMon", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.LoaiSanPham", null)
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .IsRequired()
                        .HasConstraintName("FK_LSP_TCM_LoaiSanPham");

                    b.HasOne("CoffeeShopManagement.Models.TuyChonMon", null)
                        .WithMany()
                        .HasForeignKey("MaTuyChon")
                        .IsRequired()
                        .HasConstraintName("FK_LSP_TCM_TuyChonMon");
                });

            modelBuilder.Entity("ProductProductTopping", b =>
                {
                    b.HasOne("CoffeeShopManagement.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK_ProductProductTopping_Product");

                    b.HasOne("CoffeeShopManagement.Models.ProductTopping", null)
                        .WithMany()
                        .HasForeignKey("ToppingId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductProductTopping_Topping");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.ChiTietHoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDonLuaChons");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.Combo", b =>
                {
                    b.Navigation("ChiTietCombos");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.LuaChonMon", b =>
                {
                    b.Navigation("ChiTietHoaDonLuaChons");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ProductOptions");

                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.TuyChonMon", b =>
                {
                    b.Navigation("LuaChonMons");
                });

            modelBuilder.Entity("CoffeeShopManagement.Models.Voucher", b =>
                {
                    b.Navigation("KhachHangVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
